### ISSUE TITLE
Steam Deck Incompatibility

### ISSUE THREAD

**Issue by KazWolfe** [KazWolfe/XIVBatteryGauge#1]
It appears as though BatteryGauge is incompatible with the Steam Deck. 

This incompatibility appears to be a upstream (Wine) bug. The code for Wine pulling in battery information is available [here](https://github.com/wine-mirror/wine/blob/1d178982ae5a73b18f367026c8689b56789c39fd/dlls/ntdll/unix/system.c#L3443), but it only reads from `AC` and `BAT0`. The Steam Deck, however, only has the following:

    (deck@steamdeck ~)$ ls /sys/class/power_supply/
    ACAD  BAT1

This bug will need to be fixed with Wine, brought into Proton/ProtonFixes, and *then* I will be able to look at getting BatteryGauge to work on the Steam Deck.

**Comment by KazWolfe** [comment]
Opened [Bug #52831](https://bugs.winehq.org/show_bug.cgi?id=52831) with Wine to track this.

**Comment by Kalidibus** [comment]
Is a certain version of proton needed for this to work on steam deck? Sounds like the fix was done upstream but I still get the "incompatible device" error
