### ISSUE TITLE
BatteryGauge display changed since update.

### ISSUE THREAD

**Issue by Komachii** [KazWolfe/XIVBatteryGauge#6]
Hej!

Before the patch and subsequent update of this plug-in, the plug-in used to display the percentage and remaining time as ‘50% 2h20m’ as an example.
But after the update it shows as ‘Battery is discharging.Current percentage: 50%Remaining life: 2h 20m’

Is there a way to return the way it displays to the previous more concise form?

Thank you very much in advance!

Edit: I would like to add that when charging the steam deck, the text does show up in a concise manner. But upon removing the charging cable, it goes back to the more elaborate line of text.

**Comment by KazWolfe** [comment]
Hiya! This was an inadvertent bug in the version 1.1.0 release. I've patched the bug in 2773611, and have published this as Version 1.1.1.

This fix should be rolling out to Dalamud after the PAC verifies and approves the changes. You can track that PR here: https://github.com/goatcorp/DalamudPluginsD17/pull/2671.

Apologies for letting this slip through!
