### ISSUE TITLE
Please update for 7.1!

### ISSUE THREAD

**Issue by rstuke82** [KazWolfe/XIVBatteryGauge#8]
The plugin is showing outdated on current Dalamud version.

**Comment by wompscode** [comment]
About a week ago I had submitted a pull request (#7) to get it functioning on the latest version of Dalamud, just waiting for it to get merged.

**Comment by rstuke82** [comment]
> About a week ago I had submitted a pull request (#7) to get it functioning on the latest version of Dalamud, just waiting for it to get merged.

Great!  Thanks so much for your work.

**Comment by KazWolfe** [comment]
Hi, apologies for the delay in getting this plugin back online. I've been focusing on other things and didn't have time to get it updated.

With that said, I've merged the PR from @wompscode and will be releasing it some time later tonight or tomorrow morning (PT).
